### ISSUE TITLE
my pc dosent work

### ISSUE THREAD

**Issue by tescomealdealll** [Oberonskii/Twitch-Account-Creator#2]
after running my pc dosent boot **_HELP_**

**Comment by Oberonskii** [comment]
Bro I know you. Stop saying that shit. You can look in the code. It doesnt contain anything, that will hurt your pc

**Comment by tescomealdealll** [comment]
stop lying i do not know you, this broke my pc

**Comment by Oberonskii** [comment]
This cant broke your pc. I just think you opened an exe, where you didnt know that it is a virus…

**Comment by tescomealdealll** [comment]
this program is virus my pc dosent work i am on  phone rn

**Comment by Oberonskii** [comment]
Stop saying that shit

**Comment by Oberonskii** [comment]
You just opened FreeVbucksNoVirus.exe

**Comment by tescomealdealll** [comment]
i have v-bucks generator and it is working

**Comment by Oberonskii** [comment]
Yeah of course. Maybe unchecked
